dist: trusty
sudo: required

services:
  - docker

language: generic

install:
  - docker build -t travis-docker-test:latest .

after_success:
  - docker run --entrypoint=cat travis-docker-test:latest hello.txt
